name = "tg-image-host"
compatibility_date = "2023-05-18"
pages_build_output_dir = "public"

[env.production.vars]
# 这些变量需要在Cloudflare Pages控制台中设置
# TELEGRAM_BOT_TOKEN = "your_bot_token_here"
# TELEGRAM_CHANNEL_ID = "@your_channel_username"
# MAX_FILE_SIZE = "5242880"