name = "tg-image-host"
compatibility_date = "2023-05-18"
pages_build_output_dir = "public"

# KV命名空间绑定（可选，用于存储图片URL映射）
[[kv_namespaces]]
binding = "IMAGE_STORE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

[env.production.vars]
# 这些变量需要在Cloudflare Pages控制台中设置
# TELEGRAM_BOT_TOKEN = "your_bot_token_here"
# TELEGRAM_GROUP_ID = "-1001234567890"  # 私有频道
# TELEGRAM_CHANNEL_ID = "@your_channel_username"  # 公开频道
# MAX_FILE_SIZE = "5242880"
# CF_PAGES_URL = "your-domain.pages.dev"  # 可选，用于自定义域名